export interface Issue {
  id: string;
  title: string;
  description: string;
  assignee: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'todo' | 'in-progress' | 'review' | 'done' | 'blocked';
  dueDate?: string;
  meetingId?: string;
  createdAt: string;
  updatedAt: string;
  estimatedHours?: number;
  timeTracked?: number;
  tags?: string[];
  comments?: IssueComment[];
  attachments?: string[];
  source: IssueSource;
  autoGenerated: boolean;
  relatedMeetingRecord?: MeetingReference;
}

export interface IssueComment {
  id: string;
  author: string;
  content: string;
  createdAt: string;
  updatedAt?: string;
}

export interface IssueSource {
  type: 'slack' | 'voice' | 'manual' | 'ai_recommendation';
  reference: string;
  extractedFrom?: string;
}

export interface MeetingReference {
  topic: string;
  participants: string[];
  keyPoints: string[];
  actionItems: string[];
  conclusion: string;
}

export interface IssueFilter {
  status?: string;
  assignee?: string;
  priority?: string;
  search?: string;
  tags?: string[];
  dateRange?: {
    start: string;
    end: string;
  };
}

export interface IssueStats {
  total: number;
  todo: number;
  inProgress: number;
  review: number;
  done: number;
  blocked: number;
}